export interface StockInfo {
  symbol: string;
  name: string;
  exchange: string;
  basePrice: number;
  sector: string;
  currency: string;
  currencySymbol: string;
  region: string;
}

export const STOCKS: StockInfo[] = [
  // NIFTY 50 - Banking & Finance
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank Ltd",
    exchange: "NSE",
    basePrice: 1780,
    sector: "Banking",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank Ltd",
    exchange: "NSE",
    basePrice: 1230,
    sector: "Banking",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "SBIN",
    name: "State Bank of India",
    exchange: "NSE",
    basePrice: 820,
    sector: "Banking",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "KOTAKBANK",
    name: "Kotak Mahindra Bank",
    exchange: "NSE",
    basePrice: 1920,
    sector: "Banking",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "AXISBANK",
    name: "Axis Bank Ltd",
    exchange: "NSE",
    basePrice: 1150,
    sector: "Banking",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "BAJFINANCE",
    name: "Bajaj Finance Ltd",
    exchange: "NSE",
    basePrice: 7250,
    sector: "Finance",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "BAJAJFINSV",
    name: "Bajaj Finserv Ltd",
    exchange: "NSE",
    basePrice: 1740,
    sector: "Finance",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "INDUSINDBK",
    name: "IndusInd Bank Ltd",
    exchange: "NSE",
    basePrice: 1080,
    sector: "Banking",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "HDFCLIFE",
    name: "HDFC Life Insurance",
    exchange: "NSE",
    basePrice: 720,
    sector: "Insurance",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "SBILIFE",
    name: "SBI Life Insurance",
    exchange: "NSE",
    basePrice: 1510,
    sector: "Insurance",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // IT
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    exchange: "NSE",
    basePrice: 4150,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "INFY",
    name: "Infosys Ltd",
    exchange: "NSE",
    basePrice: 1890,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "WIPRO",
    name: "Wipro Ltd",
    exchange: "NSE",
    basePrice: 580,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "HCLTECH",
    name: "HCL Technologies",
    exchange: "NSE",
    basePrice: 1820,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "TECHM",
    name: "Tech Mahindra Ltd",
    exchange: "NSE",
    basePrice: 1690,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "LTI",
    name: "LTIMindtree Ltd",
    exchange: "NSE",
    basePrice: 5450,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "MPHASIS",
    name: "Mphasis Ltd",
    exchange: "NSE",
    basePrice: 2850,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "PERSISTENT",
    name: "Persistent Systems",
    exchange: "NSE",
    basePrice: 5980,
    sector: "IT",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Energy & Oil
  {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    exchange: "NSE",
    basePrice: 2950,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ONGC",
    name: "Oil & Natural Gas Corp",
    exchange: "NSE",
    basePrice: 295,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "BPCL",
    name: "Bharat Petroleum Corp",
    exchange: "NSE",
    basePrice: 380,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "IOC",
    name: "Indian Oil Corporation",
    exchange: "NSE",
    basePrice: 175,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "GAIL",
    name: "GAIL (India) Ltd",
    exchange: "NSE",
    basePrice: 225,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "POWERGRID",
    name: "Power Grid Corp",
    exchange: "NSE",
    basePrice: 340,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "NTPC",
    name: "NTPC Ltd",
    exchange: "NSE",
    basePrice: 420,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // FMCG & Consumer
  {
    symbol: "ITC",
    name: "ITC Ltd",
    exchange: "NSE",
    basePrice: 485,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever",
    exchange: "NSE",
    basePrice: 2550,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "NESTLEIND",
    name: "Nestle India Ltd",
    exchange: "NSE",
    basePrice: 2380,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "BRITANNIA",
    name: "Britannia Industries",
    exchange: "NSE",
    basePrice: 5250,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "DABUR",
    name: "Dabur India Ltd",
    exchange: "NSE",
    basePrice: 545,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "MARICO",
    name: "Marico Ltd",
    exchange: "NSE",
    basePrice: 620,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "GODREJCP",
    name: "Godrej Consumer Products",
    exchange: "NSE",
    basePrice: 1280,
    sector: "FMCG",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Auto
  {
    symbol: "TATAMOTORS",
    name: "Tata Motors Ltd",
    exchange: "NSE",
    basePrice: 780,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "MARUTI",
    name: "Maruti Suzuki India",
    exchange: "NSE",
    basePrice: 11850,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "M&M",
    name: "Mahindra & Mahindra",
    exchange: "NSE",
    basePrice: 2950,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "BAJAJ-AUTO",
    name: "Bajaj Auto Ltd",
    exchange: "NSE",
    basePrice: 9850,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "HEROMOTOCO",
    name: "Hero MotoCorp Ltd",
    exchange: "NSE",
    basePrice: 5250,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "EICHERMOT",
    name: "Eicher Motors Ltd",
    exchange: "NSE",
    basePrice: 5100,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "TVSMOTOR",
    name: "TVS Motor Company",
    exchange: "NSE",
    basePrice: 2650,
    sector: "Auto",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Metals & Mining
  {
    symbol: "TATASTEEL",
    name: "Tata Steel Ltd",
    exchange: "NSE",
    basePrice: 145,
    sector: "Metals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "JSWSTEEL",
    name: "JSW Steel Ltd",
    exchange: "NSE",
    basePrice: 950,
    sector: "Metals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "HINDALCO",
    name: "Hindalco Industries",
    exchange: "NSE",
    basePrice: 680,
    sector: "Metals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "VEDL",
    name: "Vedanta Ltd",
    exchange: "NSE",
    basePrice: 480,
    sector: "Metals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "COALINDIA",
    name: "Coal India Ltd",
    exchange: "NSE",
    basePrice: 450,
    sector: "Metals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Pharma
  {
    symbol: "SUNPHARMA",
    name: "Sun Pharmaceutical",
    exchange: "NSE",
    basePrice: 1750,
    sector: "Pharma",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "DRREDDY",
    name: "Dr. Reddy's Labs",
    exchange: "NSE",
    basePrice: 6450,
    sector: "Pharma",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "CIPLA",
    name: "Cipla Ltd",
    exchange: "NSE",
    basePrice: 1580,
    sector: "Pharma",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "DIVISLAB",
    name: "Divi's Laboratories",
    exchange: "NSE",
    basePrice: 4250,
    sector: "Pharma",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "APOLLOHOSP",
    name: "Apollo Hospitals",
    exchange: "NSE",
    basePrice: 7200,
    sector: "Healthcare",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Infrastructure & Real Estate
  {
    symbol: "LARSEN",
    name: "Larsen & Toubro",
    exchange: "NSE",
    basePrice: 3850,
    sector: "Infrastructure",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ADANIENT",
    name: "Adani Enterprises",
    exchange: "NSE",
    basePrice: 2850,
    sector: "Conglomerate",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ADANIPORTS",
    name: "Adani Ports & SEZ",
    exchange: "NSE",
    basePrice: 1420,
    sector: "Infrastructure",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ADANIGREEN",
    name: "Adani Green Energy",
    exchange: "NSE",
    basePrice: 1950,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "DLF",
    name: "DLF Ltd",
    exchange: "NSE",
    basePrice: 920,
    sector: "Real Estate",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Telecom & Media
  {
    symbol: "BHARTIARTL",
    name: "Bharti Airtel Ltd",
    exchange: "NSE",
    basePrice: 1680,
    sector: "Telecom",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ZOMATO",
    name: "Zomato Ltd",
    exchange: "NSE",
    basePrice: 285,
    sector: "Technology",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "PAYTM",
    name: "One97 Communications",
    exchange: "NSE",
    basePrice: 580,
    sector: "Fintech",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Cement
  {
    symbol: "ULTRACEMCO",
    name: "UltraTech Cement",
    exchange: "NSE",
    basePrice: 11500,
    sector: "Cement",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "SHREECEM",
    name: "Shree Cement Ltd",
    exchange: "NSE",
    basePrice: 28500,
    sector: "Cement",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "AMBUJACEM",
    name: "Ambuja Cements",
    exchange: "NSE",
    basePrice: 680,
    sector: "Cement",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // Chemical
  {
    symbol: "PIDILITIND",
    name: "Pidilite Industries",
    exchange: "NSE",
    basePrice: 3150,
    sector: "Chemicals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "SRF",
    name: "SRF Ltd",
    exchange: "NSE",
    basePrice: 2650,
    sector: "Chemicals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  // BSE Additional
  {
    symbol: "TATAPOWER",
    name: "Tata Power Company",
    exchange: "BSE",
    basePrice: 450,
    sector: "Energy",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "TATACHEM",
    name: "Tata Chemicals Ltd",
    exchange: "BSE",
    basePrice: 1180,
    sector: "Chemicals",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "TITAN",
    name: "Titan Company Ltd",
    exchange: "NSE",
    basePrice: 3650,
    sector: "Consumer",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "ASIANPAINT",
    name: "Asian Paints Ltd",
    exchange: "NSE",
    basePrice: 2950,
    sector: "Consumer",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "BERGEPAINT",
    name: "Berger Paints India",
    exchange: "NSE",
    basePrice: 650,
    sector: "Consumer",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },
  {
    symbol: "NAUKRI",
    name: "Info Edge (Naukri)",
    exchange: "NSE",
    basePrice: 6850,
    sector: "Technology",
    currency: "INR",
    currencySymbol: "₹",
    region: "India",
  },

  // USA - NASDAQ/NYSE
  {
    symbol: "AAPL",
    name: "Apple Inc",
    exchange: "NASDAQ",
    basePrice: 213.5,
    sector: "Technology",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corp",
    exchange: "NASDAQ",
    basePrice: 415.8,
    sector: "Technology",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc",
    exchange: "NASDAQ",
    basePrice: 175.2,
    sector: "Technology",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc",
    exchange: "NASDAQ",
    basePrice: 192.4,
    sector: "E-Commerce",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corp",
    exchange: "NASDAQ",
    basePrice: 875.3,
    sector: "Semiconductors",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "META",
    name: "Meta Platforms",
    exchange: "NASDAQ",
    basePrice: 525.6,
    sector: "Technology",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc",
    exchange: "NASDAQ",
    basePrice: 175.8,
    sector: "Auto",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    exchange: "NYSE",
    basePrice: 208.5,
    sector: "Banking",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "V",
    name: "Visa Inc",
    exchange: "NYSE",
    basePrice: 288.4,
    sector: "Finance",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    exchange: "NYSE",
    basePrice: 158.2,
    sector: "Healthcare",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "WMT",
    name: "Walmart Inc",
    exchange: "NYSE",
    basePrice: 92.3,
    sector: "Retail",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "BAC",
    name: "Bank of America",
    exchange: "NYSE",
    basePrice: 38.5,
    sector: "Banking",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "XOM",
    name: "ExxonMobil Corp",
    exchange: "NYSE",
    basePrice: 112.4,
    sector: "Energy",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group",
    exchange: "NYSE",
    basePrice: 585.2,
    sector: "Healthcare",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "MA",
    name: "Mastercard Inc",
    exchange: "NYSE",
    basePrice: 498.7,
    sector: "Finance",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "PG",
    name: "Procter & Gamble",
    exchange: "NYSE",
    basePrice: 168.3,
    sector: "FMCG",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "HD",
    name: "Home Depot",
    exchange: "NYSE",
    basePrice: 385.6,
    sector: "Retail",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc",
    exchange: "NASDAQ",
    basePrice: 182.4,
    sector: "Semiconductors",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "KO",
    name: "Coca-Cola Co",
    exchange: "NYSE",
    basePrice: 68.2,
    sector: "FMCG",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "NFLX",
    name: "Netflix Inc",
    exchange: "NASDAQ",
    basePrice: 628.5,
    sector: "Media",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "ADBE",
    name: "Adobe Inc",
    exchange: "NASDAQ",
    basePrice: 452.3,
    sector: "Software",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "CRM",
    name: "Salesforce Inc",
    exchange: "NYSE",
    basePrice: 295.8,
    sector: "Software",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "ORCL",
    name: "Oracle Corp",
    exchange: "NYSE",
    basePrice: 138.5,
    sector: "Software",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    exchange: "NASDAQ",
    basePrice: 162.4,
    sector: "Semiconductors",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "INTC",
    name: "Intel Corp",
    exchange: "NASDAQ",
    basePrice: 22.8,
    sector: "Semiconductors",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "DIS",
    name: "Walt Disney Co",
    exchange: "NYSE",
    basePrice: 98.5,
    sector: "Media",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "PYPL",
    name: "PayPal Holdings",
    exchange: "NASDAQ",
    basePrice: 72.3,
    sector: "Fintech",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "GS",
    name: "Goldman Sachs",
    exchange: "NYSE",
    basePrice: 545.2,
    sector: "Banking",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "BABA",
    name: "Alibaba Group",
    exchange: "NYSE",
    basePrice: 82.5,
    sector: "E-Commerce",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },
  {
    symbol: "PFE",
    name: "Pfizer Inc",
    exchange: "NYSE",
    basePrice: 28.4,
    sector: "Pharma",
    currency: "USD",
    currencySymbol: "$",
    region: "USA",
  },

  // UK - LSE
  {
    symbol: "HSBA",
    name: "HSBC Holdings",
    exchange: "LSE",
    basePrice: 742.5,
    sector: "Banking",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "BP",
    name: "BP plc",
    exchange: "LSE",
    basePrice: 482.3,
    sector: "Energy",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "RIO",
    name: "Rio Tinto plc",
    exchange: "LSE",
    basePrice: 5285.0,
    sector: "Metals",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "AZN",
    name: "AstraZeneca",
    exchange: "LSE",
    basePrice: 12450.0,
    sector: "Pharma",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "SHEL",
    name: "Shell plc",
    exchange: "LSE",
    basePrice: 2680.0,
    sector: "Energy",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "LLOY",
    name: "Lloyds Banking",
    exchange: "LSE",
    basePrice: 58.4,
    sector: "Banking",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "ULVR",
    name: "Unilever plc",
    exchange: "LSE",
    basePrice: 4285.0,
    sector: "FMCG",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "DGE",
    name: "Diageo plc",
    exchange: "LSE",
    basePrice: 2485.0,
    sector: "FMCG",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "GSK",
    name: "GSK plc",
    exchange: "LSE",
    basePrice: 1685.0,
    sector: "Pharma",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },
  {
    symbol: "VOD",
    name: "Vodafone Group",
    exchange: "LSE",
    basePrice: 72.8,
    sector: "Telecom",
    currency: "GBP",
    currencySymbol: "£",
    region: "UK",
  },

  // Japan - TSE
  {
    symbol: "7203",
    name: "Toyota Motor Corp",
    exchange: "TSE",
    basePrice: 2850.0,
    sector: "Auto",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "6758",
    name: "Sony Group Corp",
    exchange: "TSE",
    basePrice: 12450.0,
    sector: "Technology",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "9984",
    name: "SoftBank Group",
    exchange: "TSE",
    basePrice: 8620.0,
    sector: "Technology",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "7974",
    name: "Nintendo Co Ltd",
    exchange: "TSE",
    basePrice: 8250.0,
    sector: "Technology",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "6501",
    name: "Hitachi Ltd",
    exchange: "TSE",
    basePrice: 12850.0,
    sector: "Conglomerate",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "8306",
    name: "Mitsubishi UFJ",
    exchange: "TSE",
    basePrice: 1285.0,
    sector: "Banking",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "9432",
    name: "NTT Corp",
    exchange: "TSE",
    basePrice: 152.0,
    sector: "Telecom",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "4063",
    name: "Shin-Etsu Chemical",
    exchange: "TSE",
    basePrice: 5250.0,
    sector: "Chemicals",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "6367",
    name: "Daikin Industries",
    exchange: "TSE",
    basePrice: 18500.0,
    sector: "Manufacturing",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },
  {
    symbol: "7267",
    name: "Honda Motor Co",
    exchange: "TSE",
    basePrice: 1485.0,
    sector: "Auto",
    currency: "JPY",
    currencySymbol: "¥",
    region: "Japan",
  },

  // China - SSE/SZSE
  {
    symbol: "601398",
    name: "ICBC",
    exchange: "SSE",
    basePrice: 5.85,
    sector: "Banking",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "600519",
    name: "Kweichow Moutai",
    exchange: "SSE",
    basePrice: 1682.5,
    sector: "FMCG",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "601857",
    name: "PetroChina",
    exchange: "SSE",
    basePrice: 8.92,
    sector: "Energy",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "000858",
    name: "Wuliangye Yibin",
    exchange: "SZSE",
    basePrice: 125.8,
    sector: "FMCG",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "601288",
    name: "Agricultural Bank",
    exchange: "SSE",
    basePrice: 4.58,
    sector: "Banking",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "600036",
    name: "China Merchants Bank",
    exchange: "SSE",
    basePrice: 38.5,
    sector: "Banking",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "601318",
    name: "Ping An Insurance",
    exchange: "SSE",
    basePrice: 48.2,
    sector: "Insurance",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },
  {
    symbol: "002594",
    name: "BYD Co Ltd",
    exchange: "SZSE",
    basePrice: 285.4,
    sector: "Auto",
    currency: "CNY",
    currencySymbol: "¥",
    region: "China",
  },

  // Germany - FSE/XETRA
  {
    symbol: "SAP",
    name: "SAP SE",
    exchange: "FSE",
    basePrice: 198.5,
    sector: "Software",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "SIE",
    name: "Siemens AG",
    exchange: "FSE",
    basePrice: 182.4,
    sector: "Manufacturing",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "ALV",
    name: "Allianz SE",
    exchange: "FSE",
    basePrice: 295.8,
    sector: "Insurance",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "BAYN",
    name: "Bayer AG",
    exchange: "FSE",
    basePrice: 28.5,
    sector: "Pharma",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "BMW",
    name: "BMW AG",
    exchange: "FSE",
    basePrice: 82.4,
    sector: "Auto",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "DTE",
    name: "Deutsche Telekom",
    exchange: "FSE",
    basePrice: 28.2,
    sector: "Telecom",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "DBK",
    name: "Deutsche Bank",
    exchange: "FSE",
    basePrice: 15.8,
    sector: "Banking",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },
  {
    symbol: "VOW3",
    name: "Volkswagen AG",
    exchange: "FSE",
    basePrice: 112.5,
    sector: "Auto",
    currency: "EUR",
    currencySymbol: "€",
    region: "Germany",
  },

  // Hong Kong - HKEX
  {
    symbol: "700",
    name: "Tencent Holdings",
    exchange: "HKEX",
    basePrice: 382.4,
    sector: "Technology",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "9988",
    name: "Alibaba Group HK",
    exchange: "HKEX",
    basePrice: 82.5,
    sector: "E-Commerce",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "1299",
    name: "AIA Group",
    exchange: "HKEX",
    basePrice: 52.85,
    sector: "Insurance",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "2318",
    name: "Ping An Insurance HK",
    exchange: "HKEX",
    basePrice: 42.5,
    sector: "Insurance",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "1",
    name: "CKH Holdings",
    exchange: "HKEX",
    basePrice: 48.2,
    sector: "Conglomerate",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "5",
    name: "HSBC Holdings HK",
    exchange: "HKEX",
    basePrice: 58.5,
    sector: "Banking",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "2",
    name: "CLP Holdings",
    exchange: "HKEX",
    basePrice: 72.8,
    sector: "Energy",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },
  {
    symbol: "941",
    name: "China Mobile",
    exchange: "HKEX",
    basePrice: 68.4,
    sector: "Telecom",
    currency: "HKD",
    currencySymbol: "HK$",
    region: "HongKong",
  },

  // Australia - ASX
  {
    symbol: "CBA",
    name: "Commonwealth Bank",
    exchange: "ASX",
    basePrice: 128.5,
    sector: "Banking",
    currency: "AUD",
    currencySymbol: "A$",
    region: "Australia",
  },
  {
    symbol: "BHP",
    name: "BHP Group",
    exchange: "ASX",
    basePrice: 42.8,
    sector: "Metals",
    currency: "AUD",
    currencySymbol: "A$",
    region: "Australia",
  },
  {
    symbol: "CSL",
    name: "CSL Limited",
    exchange: "ASX",
    basePrice: 285.4,
    sector: "Pharma",
    currency: "AUD",
    currencySymbol: "A$",
    region: "Australia",
  },
  {
    symbol: "ANZ",
    name: "ANZ Banking Group",
    exchange: "ASX",
    basePrice: 28.5,
    sector: "Banking",
    currency: "AUD",
    currencySymbol: "A$",
    region: "Australia",
  },
  {
    symbol: "WBC",
    name: "Westpac Banking",
    exchange: "ASX",
    basePrice: 25.8,
    sector: "Banking",
    currency: "AUD",
    currencySymbol: "A$",
    region: "Australia",
  },
  {
    symbol: "NAB",
    name: "National Australia Bank",
    exchange: "ASX",
    basePrice: 34.2,
    sector: "Banking",
    currency: "AUD",
    currencySymbol: "A$",
    region: "Australia",
  },
];

export function generateHistoricalPrices(
  basePrice: number,
  days = 60,
): number[] {
  const prices: number[] = [];
  let price = basePrice * (0.85 + Math.random() * 0.1);
  for (let i = 0; i < days; i++) {
    const change = (Math.random() - 0.48) * 0.02;
    price = price * (1 + change);
    price = Math.max(price, basePrice * 0.5);
    prices.push(Math.round(price * 100) / 100);
  }
  return prices;
}

export function generateOHLC(prices: number[]) {
  return prices.map((close, i) => {
    const open = i === 0 ? close : prices[i - 1];
    const high = Math.max(open, close) * (1 + Math.random() * 0.008);
    const low = Math.min(open, close) * (1 - Math.random() * 0.008);
    const date = new Date();
    date.setDate(date.getDate() - (prices.length - i));
    return {
      date: date.toLocaleDateString("en-IN", {
        day: "2-digit",
        month: "short",
      }),
      open,
      high,
      low,
      close,
    };
  });
}

export interface LiveCandle {
  time: string; // e.g. "14:35"
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  isFuture?: boolean;
}

/** Generate intraday 1-min candles starting from market open (9:15 AM)
 *  up to current simulated time, then future=true candles for 15 min ahead */
export function generateIntradayCandles(
  basePrice: number,
  seed: number,
  includeMinutes: number, // how many minutes since 9:15 have elapsed
): LiveCandle[] {
  const candles: LiveCandle[] = [];
  // Use seeded pseudo-random for consistent per-stock data
  const rand = (i: number, salt = 0) => {
    const x = Math.sin(seed * 9999 + i * 127 + salt) * 43758.5453;
    return x - Math.floor(x);
  };

  let price = basePrice;
  const totalCandles = Math.max(includeMinutes, 15);

  for (let i = 0; i < totalCandles + 15; i++) {
    const isFuture = i >= includeMinutes;
    const hour = Math.floor((i + 9 * 60 + 15) / 60);
    const min = (i + 15) % 60;
    const time = `${String(hour).padStart(2, "0")}:${String(min).padStart(2, "0")}`;

    // Trend component: slight drift + mean reversion
    const trendBias = (rand(i, 1) - 0.47) * 0.003;
    const reversion = ((basePrice - price) / basePrice) * 0.05;
    const change = trendBias + reversion + (rand(i, 2) - 0.5) * 0.004;

    const open = price;
    price = price * (1 + change);
    price = Math.max(price, basePrice * 0.8);
    const close = price;

    const high = Math.max(open, close) * (1 + rand(i, 3) * 0.002);
    const low = Math.min(open, close) * (1 - rand(i, 4) * 0.002);
    const volume = Math.floor(rand(i, 5) * 100000 + 50000);

    candles.push({ time, open, high, low, close, volume, isFuture });
  }
  return candles;
}
