/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Trade = IDL.Record({
  'tradeType' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'symbol' : IDL.Text,
  'autoTrade' : IDL.Bool,
});
export const Stock = IDL.Record({
  'quantity' : IDL.Nat,
  'avgBuyPrice' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'balance' : IDL.Nat,
  'tradeHistory' : IDL.Vec(Trade),
  'autoTradeSettings' : IDL.Vec(IDL.Text),
  'holdings' : IDL.Vec(Stock),
  'watchlist' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'createPortfolio' : IDL.Func([], [], []),
  'getAllPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
  'getPortfolio' : IDL.Func([IDL.Principal], [Portfolio], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Trade = IDL.Record({
    'tradeType' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'symbol' : IDL.Text,
    'autoTrade' : IDL.Bool,
  });
  const Stock = IDL.Record({
    'quantity' : IDL.Nat,
    'avgBuyPrice' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'balance' : IDL.Nat,
    'tradeHistory' : IDL.Vec(Trade),
    'autoTradeSettings' : IDL.Vec(IDL.Text),
    'holdings' : IDL.Vec(Stock),
    'watchlist' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'createPortfolio' : IDL.Func([], [], []),
    'getAllPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
    'getPortfolio' : IDL.Func([IDL.Principal], [Portfolio], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };