/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Portfolio {
  'balance' : bigint,
  'tradeHistory' : Array<Trade>,
  'autoTradeSettings' : Array<string>,
  'holdings' : Array<Stock>,
  'watchlist' : Array<string>,
}
export interface Stock {
  'quantity' : bigint,
  'avgBuyPrice' : bigint,
  'symbol' : string,
}
export type Time = bigint;
export interface Trade {
  'tradeType' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'price' : bigint,
  'symbol' : string,
  'autoTrade' : boolean,
}
export interface _SERVICE {
  'createPortfolio' : ActorMethod<[], undefined>,
  'getAllPortfolios' : ActorMethod<[], Array<Portfolio>>,
  'getPortfolio' : ActorMethod<[Principal], Portfolio>,
  'isOwner' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];